<html><body><p>Hi Armin,<br><br>I can't log in to bugs.pypy.org but the problem is very easy to replicate, you only need to test this and it fails (v6.0.0 works fine but both v7.0.0 and 7.1.0 fail):<br><br>try:<br>    import sqlite3<br>except Exception as e:<br>    print str(e)<br><br>The error is:<br>'C:\pypy27v710\lib_pypy\_sqlite3_cffi.pypy-41.pyd': The specified module could not be found<br><br>I've tested it on two different Win10 PCs (32bit PyPy on 64bit Win10) and both exhibit the same behaviour.<br></p></body></html>