<html><body><p>I can't seem to compile (32-bit Ubuntu 9.10 chroot), by manually executing the Makefile in /tmp/usession-0/testing_1 I get this traceback:<br><br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 1210, in (module)<br>    tracker.process(f, g, filename=fn)<br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 229, in process<br>    lines = self.process_function(lines, entrypoint, filename)<br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 244, in process_function<br>    table = tracker.computegcmaptable(self.verbose)<br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 285, in computegcmaptable<br>    self.parse_instructions()<br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 364, in parse_instructions<br>    meth = self.find_missing_visit_method(opname)<br>  File "/home/della/pkg/pypy/trunk/pypy/translator/c/gcc/trackgcroot.py", line 390, in find_missing_visit_method<br>    raise UnrecognizedOperation(opname)<br>__main__.UnrecognizedOperation: jc<br><br>there are some type warnings also for pointers, I don't know if they could be any useful. Maybe you can help me?</p></body></html>